from graphviz import Digraph

dot = Digraph(graph_attr={'rankdir': 'LR'}, node_attr={'shape': 'box'})

dot.node('A', 'IF/ID')
dot.node('B', 'Decoder')
dot.node('C', 'Register File')
dot.node('D', 'Adder')
dot.node('E', 'SE Adder')
dot.node('F', 'Mux')
dot.node('G', 'Program Counter')
dot.node('H', 'ID/EX')
dot.node('I', 'NVZ reg')
dot.node('J', 'Mux')
dot.node('K', 'ALU')
dot.node('L', 'Shift')
dot.node('M', 'Mux')
dot.node('N', 'EX/MEM')
dot.node('O', 'TSB')
dot.node('P', 'MEM/WB')
dot.node('Q', 'Mux')
dot.node('R', 'Mux')

dot.node('I1', style='invis')
dot.node('AD', shape='point', width='0.01')
dot.node('O1', style='invis')
dot.node('B0', shape='point', width='0.01')
dot.node('FOUR', style='invis')
dot.node('ZE', shape='point', width='0.01')
dot.node('a_shift', shape='point', width='0.01')
dot.node('BW', shape='point', width='0.01')
dot.node('LslDot', shape='point', width='0.01')
dot.node('LsrDot', shape='point', width='0.01')
dot.node('daddrDot', shape='point', width='0.01')
dot.node('daddrOut', style='invis')
dot.node('dataDot', shape='point', width='0.01')
dot.node('dataOut', style='invis')
dot.node('MemWriteDot', shape='point', width='0.01')
dot.node('RMUXIN', style='invis')
dot.node('MemToRegDot', shape='point', width='0.01')

dot.node('pc_sel_or', 'OR')
dot.node('pc_sel_and1', 'AND')
dot.node('pc_sel_and2', 'AND')
dot.node('NO', 'NOT')
dot.node('EQ', '== 0')
dot.node('alu_out_or', 'OR')

dot.edge('I1', 'A', label='ibus')
dot.edge('A', 'B', label='id_if_out')
dot.edge('A', 'E', label='pc_adder_out')
dot.edge('G', 'AD', label='iaddrbus', arrowhead='none')
dot.edge('AD', 'A', label='iaddrbus')
dot.edge('AD', 'D', label='iaddrbus')
dot.edge('FOUR', 'D', label='4')
dot.edge('AD', 'O1', label='iaddrbus')
dot.edge('B', 'C', label='Aselect')
dot.edge('B', 'C', label='Bselect')
dot.edge('D', 'F')
dot.edge('E', 'F')
dot.edge('F', 'G')
dot.edge('B', 'pc_sel_or', label='Branch')
dot.edge('B', 'pc_sel_and1', label='CBZ')
dot.edge('B', 'pc_sel_and2', label='CNBZ')
dot.edge('pc_sel_and1', 'pc_sel_or')
dot.edge('pc_sel_and2', 'pc_sel_or')
dot.edge('pc_sel_or', 'F')
dot.edge('C', 'H', label='abus_value')
dot.edge('C', 'B0', label='bbus_value', arrowhead='none')
dot.edge('B0', 'EQ')
dot.edge('EQ', 'pc_sel_and1')
dot.edge('EQ', 'NO')
dot.edge('NO', 'pc_sel_and2')
dot.edge('B0', 'H')
for ele in ['Dselect', 'Imm', 'S', 'Cin', 'RegWriteD', 'MemToRegD', 'MemWriteD', 'SetFlagsD', 'LslD', 'LsrD', 'shamtD']: dot.edge('B', 'H', label=ele)
dot.edge('B', 'ZE', arrowhead='none')
dot.edge('ZE', 'H', label='ZE_Immediate')
dot.edge('ZE', 'E', label='ZE_Immediate')
dot.edge('H', 'L', label='shamt')
dot.edge('H', 'LslDot', label='LslE', arrowhead='none')
dot.edge('H', 'LsrDot', label='LsrE', arrowhead='none')
dot.edge('LslDot', 'L')
dot.edge('LsrDot', 'L')
dot.edge('H', 'a_shift', label='abus', arrowhead='none')
dot.edge('a_shift', 'L')
dot.edge('a_shift', 'K')
dot.edge('H', 'BW', arrowhead='none')
dot.edge('BW', 'J')
dot.edge('BW', 'N', label='WriteDataE')
dot.edge('H', 'J', label='ZE_Immediate')
dot.edge('J', 'K', label='bbus')
dot.edge('J', 'K', label='Imm')
dot.edge('K', 'M')
dot.edge('L', 'M')
dot.edge('LslDot', "alu_out_or")
dot.edge('LsrDot', "alu_out_or")
dot.edge('alu_out_or', 'M')
dot.edge('M', 'N')
dot.edge('H', 'N', label='Dselect')
dot.edge('H', 'K', label='S')
dot.edge('H', 'K', label='Cin')
for ele in ['N', 'V', 'Z']: dot.edge('K', 'I', label=ele)
dot.edge('I', 'B')
dot.edge('H', 'I', label='SetFlags')
for ele in ['RegWriteE', 'MemToRegE', 'MemWriteE']: dot.edge('H', 'N', label=ele)
dot.edge('N', 'daddrDot', label='daddrbus', arrowhead='none')
dot.edge('daddrDot', 'daddrOut', label='daddrbus')
dot.edge('daddrDot', 'P')
dot.edge('N', 'dataDot', arrowhead='none')
dot.edge('dataDot', 'P')
dot.edge('dataDot', 'O', label='databus', dir='both')
dot.edge('O', 'dataOut', label='databus', dir='both')
for ele in ['Dselect', 'RegWriteM']: dot.edge('N', 'P', label=ele)
dot.edge('N', 'MemWriteDot', label='MemWrite', arrowhead='none')
dot.edge('MemWriteDot', 'O')
dot.edge('MemWriteDot', 'P')
for ele in ['daddrbus', 'databus']: dot.edge('P', 'Q', label=ele)
dot.edge('P', 'R', label='Dselect')
dot.edge('RMUXIN', 'R', label='2^31')
dot.edge('P', 'MemToRegDot', label='MemToReg')
dot.edge('MemToRegDot', 'Q')
dot.edge('MemToRegDot', 'R')
dot.edge('Q', 'C')
dot.edge('R', 'C')

dot.render('my_graph', format='png', cleanup=True)
